apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: litecoin
spec:
  serviceName: "litecoin"
  selector:
    matchLabels:
      app: litecoin
  replicas: 1
  template:
    metadata:
      labels:
        app: litecoin
    spec:
      securityContext:
        runAsUser: 100
        runAsGroup: 101
        fsGroup: 101
      terminationGracePeriodSeconds: 10
      containers:
      - name: litecoin
        image: darron/kraken
        volumeMounts:
        - name: data
          mountPath: /home/litecoin/.litecoin
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 128Mi
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "do-block-storage"
      resources:
        requests:
          storage: 1Gi